"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

const field="w-full rounded-xl border border-[var(--line)] bg-[#0b0d12] px-4 py-3 text-white placeholder:text-[#616876]";

export function AdminNetworkImport(){const router=useRouter();const [state,setState]=useState<"idle"|"loading"|"done"|"error">("idle");const [message,setMessage]=useState("");async function change(file?:File){if(!file)return;setState("loading");try{const contacts=JSON.parse(await file.text());const response=await fetch("/api/admin/network",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"replace",contacts})});const data=await response.json();if(!response.ok)throw new Error();setMessage(`${data.count} contatos sincronizados com segurança.`);setState("done");router.refresh();}catch{setMessage("Arquivo inválido. Use o connections.json criado pelo extrator.");setState("error");}}return <div><label className="block cursor-pointer rounded-2xl border border-dashed border-[#465174] bg-[#0d111d] p-5 text-center"><span className="block font-medium text-white">Importar rede do LinkedIn</span><span className="mt-2 block text-xs leading-5 text-[var(--muted)]">O arquivo aceita formação, empresas e experiência internacional opcionais. Mensagens e redes dos demais administradores são preservadas.</span><input type="file" accept="application/json" className="mt-4 block w-full text-sm" disabled={state==="loading"} onChange={event=>change(event.target.files?.[0])}/></label><a href="/network-profile-template.json" download className="mt-3 inline-flex min-h-11 items-center text-xs text-[#9eb2ff]">Baixar modelo de histórico enriquecido ↓</a>{message&&<p role="status" className={`mt-3 text-sm ${state==="error"?"text-[var(--danger)]":"text-[var(--green)]"}`}>{message}</p>}</div>}

export function PublicDiscovery(){const router=useRouter();const [loading,setLoading]=useState(false);const [message,setMessage]=useState("");async function run(){setLoading(true);setMessage("");try{const response=await fetch("/api/admin/network/enrich",{method:"POST"});const data=await response.json();if(!response.ok)throw new Error();setMessage(data.workflowId?`Orquestrador ativado: ${data.profiles} perfis serão pesquisados e ${data.jobs} vagas reranqueadas em segundo plano.`:"Todos os perfis já foram verificados nos últimos 30 dias.");router.refresh();}catch{setMessage("Não foi possível iniciar a fila agora. Nenhum dado existente foi alterado.");}finally{setLoading(false);}}return <div className="rounded-2xl border border-[#405078] bg-[#101528] p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">Descoberta pública assistida por IA</p><p className="mt-1 max-w-2xl text-xs leading-5 text-[var(--muted)]">O orquestrador pesquisa até 8 perfis em paralelo, valida fontes e atualiza as vagas sem bloquear esta tela.</p></div><button type="button" onClick={run} disabled={loading} className="accent-button min-h-12 shrink-0 rounded-xl px-5 text-sm font-medium disabled:opacity-50">{loading?"Criando pipeline…":"Encontrar informações"}</button></div>{message&&<p role="status" className="mt-3 text-xs text-[#aebfff]">{message}</p>}<p className="mt-3 text-[10px] leading-4 text-[var(--muted)]">Ao executar, nome e contexto profissional são enviados para busca pública com retenção zero exigida do provedor. CV continua totalmente opcional. Acompanhe custos, fontes e falhas em Inteligência.</p></div>}

export function ManualAdminContact(){const router=useRouter();const [loading,setLoading]=useState(false);const [error,setError]=useState("");async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setLoading(true);setError("");const body={mode:"manual",...Object.fromEntries(new FormData(form))};const response=await fetch("/api/admin/network",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok){setError("Confira o nome e o WhatsApp com DDD e código do país.");setLoading(false);return;}form.reset();setLoading(false);router.refresh();}return <form onSubmit={submit} className="grid gap-3 md:grid-cols-2"><label className="text-xs text-[var(--muted)]">Nome<input name="name" required className={`${field} mt-2`} placeholder="Carlos Almeida"/></label><label className="text-xs text-[var(--muted)]">WhatsApp<input name="phone" required inputMode="tel" className={`${field} mt-2`} placeholder="+55 11… ou +1 415…"/></label><label className="text-xs text-[var(--muted)] md:col-span-2">Contexto profissional<input name="headline" className={`${field} mt-2`} placeholder="Head of Engineering · Fintech"/></label><label className="text-xs text-[var(--muted)] md:col-span-2">Histórico relevante<textarea name="profileContext" rows={3} className={`${field} mt-2 resize-y`} placeholder="ITA · ex-McKinsey · experiência nos Estados Unidos"/><span className="mt-1 block text-[10px] leading-4">Formação, empresas anteriores e experiência internacional. Use somente informações profissionais verificáveis.</span></label>{error&&<p role="alert" className="text-sm text-[var(--danger)] md:col-span-2">{error}</p>}<button disabled={loading} className="accent-button min-h-12 rounded-xl px-5 text-sm font-medium md:w-fit">{loading?"Salvando…":"Adicionar contato"}</button></form>}
