"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

const field="w-full rounded-xl border border-[var(--line)] bg-[#0b0d12] px-4 py-3 text-white placeholder:text-[#616876]";

export function AdminNetworkImport(){const router=useRouter();const [state,setState]=useState<"idle"|"loading"|"done"|"error">("idle");const [message,setMessage]=useState("");async function change(file?:File){if(!file)return;setState("loading");try{const contacts=JSON.parse(await file.text());const response=await fetch("/api/admin/network",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"replace",contacts})});const data=await response.json();if(!response.ok)throw new Error();setMessage(`${data.count} contatos sincronizados com segurança.`);setState("done");router.refresh();}catch{setMessage("Arquivo inválido. Use o connections.json criado pelo extrator.");setState("error");}}return <div><label className="block cursor-pointer rounded-2xl border border-dashed border-[#465174] bg-[#0d111d] p-5 text-center"><span className="block font-medium text-white">Importar rede do LinkedIn</span><span className="mt-2 block text-xs leading-5 text-[var(--muted)]">O arquivo atualiza apenas a sua rede. Mensagens e redes dos demais administradores são preservadas.</span><input type="file" accept="application/json" className="mt-4 block w-full text-sm" disabled={state==="loading"} onChange={event=>change(event.target.files?.[0])}/></label>{message&&<p role="status" className={`mt-3 text-sm ${state==="error"?"text-[var(--danger)]":"text-[var(--green)]"}`}>{message}</p>}</div>}

export function ManualAdminContact(){const router=useRouter();const [loading,setLoading]=useState(false);const [error,setError]=useState("");async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setLoading(true);setError("");const body={mode:"manual",...Object.fromEntries(new FormData(form))};const response=await fetch("/api/admin/network",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok){setError("Confira o nome e o WhatsApp com DDD.");setLoading(false);return;}form.reset();setLoading(false);router.refresh();}return <form onSubmit={submit} className="grid gap-3 md:grid-cols-2"><label className="text-xs text-[var(--muted)]">Nome<input name="name" required className={`${field} mt-2`} placeholder="Carlos Almeida"/></label><label className="text-xs text-[var(--muted)]">WhatsApp<input name="phone" required inputMode="tel" className={`${field} mt-2`} placeholder="+55 11 98765-4321"/></label><label className="text-xs text-[var(--muted)] md:col-span-2">Contexto profissional<input name="headline" className={`${field} mt-2`} placeholder="Head of Engineering · Fintech"/></label>{error&&<p role="alert" className="text-sm text-[var(--danger)] md:col-span-2">{error}</p>}<button disabled={loading} className="accent-button min-h-12 rounded-xl px-5 text-sm font-medium md:w-fit">{loading?"Salvando…":"Adicionar contato"}</button></form>}
