"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

const inputClass="w-full rounded-xl border border-[var(--line)] bg-[#0b0d12] px-4 py-3 text-sm text-white placeholder:text-[#616876]";

export function CreateJobForm() {
  const router=useRouter(); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;setLoading(true);setError("");const form=new FormData(formElement);const body=Object.fromEntries(form);const response=await fetch("/api/admin/jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok){setError("Não foi possível criar a vaga.");setLoading(false);return;}const data=await response.json();formElement.reset();router.push(`/admin/vagas/${data.id}`);router.refresh();}
  return <form onSubmit={submit} className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><label className="text-xs text-[var(--muted)]">Cargo<input name="title" required className={`${inputClass} mt-2`} placeholder="Staff Backend Engineer"/></label><label className="text-xs text-[var(--muted)]">Empresa<input name="company" required className={`${inputClass} mt-2`} placeholder="Sua empresa"/></label></div><label className="block text-xs text-[var(--muted)]">Localização<input name="location" className={`${inputClass} mt-2`} placeholder="São Paulo · Híbrido"/></label><label className="block text-xs text-[var(--muted)]">Descrição da vaga<textarea name="description" required rows={7} className={`${inputClass} mt-2 resize-y`} placeholder="Responsabilidades, requisitos e contexto da equipe…"/></label><label className="block text-xs text-[var(--muted)]">Publicação<select name="status" defaultValue="open" className={`${inputClass} mt-2`}><option value="open">Abrir e buscar pessoas agora</option><option value="draft">Salvar como rascunho</option></select></label><div className="rounded-xl border border-[#3b4563] bg-[#111729] p-3 text-xs leading-5 text-[#b9c5e9]">✦ A inteligência estrutura competências, senioridade e contexto para comparar a vaga com as redes da equipe.</div>{error&&<p className="text-sm text-[var(--danger)]">{error}</p>}<button disabled={loading} className="accent-button min-h-12 w-full rounded-xl px-5 py-3 text-sm font-medium sm:w-auto">{loading?"Publicando…":"Cadastrar vaga"}</button></form>;
}

export function InviteForm() {
  const router=useRouter(); const [email,setEmail]=useState(""); const [link,setLink]=useState(""); const [loading,setLoading]=useState(false); const [copied,setCopied]=useState(false);
  async function submit(event:React.FormEvent){event.preventDefault();setLoading(true);const response=await fetch("/api/admin/invitations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:email||undefined})});const data=await response.json();setLink(data.url);setLoading(false);router.refresh();}
  async function copy(){await navigator.clipboard.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),1800);}
  return <div>{!link?<form onSubmit={submit} className="flex flex-col gap-3 sm:flex-row"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} className={inputClass} placeholder="colega@empresa.com (opcional)"/><button disabled={loading} className="accent-button min-h-12 shrink-0 rounded-xl px-5 py-3 text-sm font-medium">{loading?"Criando…":"Criar convite"}</button></form>:<div className="rounded-xl border border-[#42527d] bg-[#10172a] p-4"><p className="text-xs text-[#aebce8]">Convite criado. Compartilhe este link somente com a pessoa desejada:</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input readOnly value={link} className={`${inputClass} min-w-0 font-mono text-xs`}/><button type="button" onClick={copy} className="min-h-11 shrink-0 rounded-xl border border-[#526595] px-4 text-xs text-white">{copied?"Copiado ✓":"Copiar"}</button></div><button type="button" onClick={()=>{setLink("");setEmail("")}} className="mt-3 min-h-11 text-xs text-[var(--muted)]">Criar outro convite</button></div>}<p className="mt-3 text-xs leading-5 text-[var(--muted)]">O link expira em 7 dias. O membro verá apenas as próprias oportunidades e controla cada indicação.</p></div>;
}

export function ReferralStatus({id,current}:{id:string;current:string}) { const router=useRouter(); const [value,setValue]=useState(current); async function change(next:string){setValue(next);await fetch(`/api/admin/referrals/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:next})});router.refresh();} return <select aria-label="Status da indicação" value={value} onChange={e=>change(e.target.value)} className="min-h-11 w-full rounded-lg border border-[var(--line)] bg-[#0b0d12] px-3 py-2 text-xs md:w-auto"><option value="submitted">Recebida</option><option value="reviewing">Em análise</option><option value="contacted">Contato iniciado</option><option value="declined">Não avançou</option><option value="hired">Contratada</option></select>; }
