"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

const field="w-full rounded-xl border border-[var(--line)] bg-[#0b0d12] px-4 py-3 text-sm text-white placeholder:text-[#616876]";

export function JoinForm({token,email}:{token:string;email:string|null}) { const router=useRouter(); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);const body=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch(`/api/join/${token}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok){const data=await response.json();setError(data.error==="EMAIL_MISMATCH"?"Este convite pertence a outro e-mail.":"Este convite expirou ou já foi usado.");setLoading(false);return;}router.push("/app");router.refresh();} return <form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-xs text-[var(--muted)]">Seu nome<input name="name" required minLength={2} className={`${field} mt-2`} placeholder="Como devemos chamar você?"/></label><label className="block text-xs text-[var(--muted)]">E-mail<input name="email" type="email" required defaultValue={email??""} readOnly={!!email} className={`${field} mt-2 read-only:opacity-70`}/></label>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}<button disabled={loading} className="accent-button w-full rounded-xl px-5 py-3.5 font-medium">{loading?"Ativando…":"Aceitar convite e continuar"}</button></form> }

export function LinkedInUpload() { const router=useRouter(); const [file,setFile]=useState<File|null>(null); const [state,setState]=useState<"idle"|"loading"|"done"|"error">("idle"); async function upload(){if(!file)return;setState("loading");const data=new FormData();data.append("file",file);const response=await fetch("/api/member/linkedin",{method:"POST",body:data});setState(response.ok?"done":"error");if(response.ok)router.refresh();} return <div><label className="block overflow-hidden rounded-xl border border-dashed border-[#465174] bg-[#0d111d] p-4 text-center text-sm text-[var(--muted)] sm:p-5"><span className="mb-2 block text-white">Selecione seu `connections.json`</span><span className="text-xs">O arquivo é processado para a sua área privada.</span><input type="file" accept="application/json" className="mt-4 block max-w-full text-xs" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button type="button" onClick={upload} disabled={!file||state==="loading"} className="accent-button mt-3 min-h-12 w-full rounded-xl px-5 py-3 text-sm font-medium disabled:opacity-40 sm:w-auto">{state==="loading"?"Mapeando sua rede…":state==="done"?"Rede conectada ✓":"Importar minha rede"}</button>{state==="error"&&<p className="mt-2 text-xs text-[var(--danger)]">Arquivo inválido. Use o JSON gerado pelo extrator guiado.</p>}</div> }

export function ReferralCandidate({jobId,name,headline,linkedinUrl,evidence,score}:{jobId:string;name:string;headline:string|null;linkedinUrl:string|null;evidence:string[];score:number}) { const router=useRouter(); const [open,setOpen]=useState(false); const [sent,setSent]=useState(false); async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const note=String(new FormData(event.currentTarget).get("note")??"");const response=await fetch("/api/member/referrals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId,candidateName:name,candidateHeadline:headline,linkedinUrl,relationshipNote:note})});if(response.ok){setSent(true);router.refresh();}} return <article className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-start justify-between gap-3 sm:gap-4"><div className="min-w-0"><p className="font-medium break-words">{name}</p><p className="mt-1 text-sm text-[var(--muted)] break-words">{headline||"Perfil com informações limitadas"}</p></div><div className="shrink-0 rounded-xl border border-[#405078] bg-[#11182a] px-3 py-2 text-center"><p className="text-lg text-[#aebfff]">{Math.round(score*100)}%</p><p className="text-[8px] uppercase tracking-wider text-[var(--muted)]">aderência</p></div></div>{evidence.length>0&&<div className="mt-4 rounded-xl border border-[#3a4260] bg-[#0d111c] p-3"><p className="font-mono text-[9px] uppercase tracking-wider text-[#8ea7ff]">Por que esta pessoa?</p><ul className="mt-2 space-y-1 text-xs text-[#aeb4c0]">{evidence.slice(0,3).map(item=><li key={item}>· {item}</li>)}</ul></div>}{sent?<p className="mt-4 text-sm text-[var(--green)]">Indicação compartilhada com consentimento ✓</p>:!open?<button type="button" onClick={()=>setOpen(true)} className="mt-4 min-h-11 w-full rounded-xl border border-[#536595] px-4 py-2.5 text-sm text-white hover:bg-[#171d2d] sm:w-auto">Quero indicar</button>:<form onSubmit={submit} className="mt-4 space-y-3"><label className="block text-xs text-[var(--muted)]">Como você conhece esta pessoa?<textarea name="note" required minLength={10} rows={3} className={`${field} mt-2`} placeholder="Trabalhamos juntos por dois anos…"/></label><div className="rounded-lg bg-[#15251f] p-3 text-[10px] leading-4 text-[#93d7bd]">Ao confirmar, você compartilha nome, perfil profissional e esta nota com o administrador.</div><button className="accent-button min-h-11 w-full rounded-xl px-4 py-2.5 text-sm sm:w-auto">Confirmar indicação</button></form>}</article> }
