import Link from "next/link";
import { MetricCard, PageHeader } from "@/components/platform/AppShell";
import { dashboardMetrics, listJobs, listReferrals } from "@/lib/platform/repository";

export default async function AdminDashboard() {
  const [metrics,jobs,referrals] = await Promise.all([dashboardMetrics(),listJobs(),listReferrals()]);
  return <><PageHeader eyebrow="Inteligência de indicação" title="Bom dia, administrador." description="Sua equipe transforma relações de confiança em candidatos relevantes — sem expor redes privadas." action={<Link href="/admin/vagas?nova=1" className="accent-button min-h-12 content-center rounded-xl px-5 py-3 text-center text-sm font-medium">+ Nova vaga</Link>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Vagas ativas" value={metrics.activeJobs} hint="Prontas para receber indicações"/><MetricCard label="Equipe ativada" value={metrics.members} hint={`${metrics.pendingInvites} convites pendentes`} tone="green"/><MetricCard label="Indicações" value={metrics.referrals} hint="Compartilhadas com consentimento" tone="violet"/><MetricCard label="Privacidade" value="100%" hint="Nenhuma rede exposta" tone="amber"/></div><div className="mt-7 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4 sm:p-5"><div className="flex flex-col items-start gap-3 min-[400px]:flex-row min-[400px]:items-center min-[400px]:justify-between"><div><h2 className="font-medium">Vagas em movimento</h2><p className="mt-1 text-xs text-[var(--muted)]">Acompanhe onde a rede está gerando valor.</p></div><Link href="/admin/vagas" className="min-h-11 content-center text-xs text-[#9eb2ff]">Ver todas →</Link></div><div className="mt-5 space-y-3">{jobs.length===0?<Empty text="Crie a primeira vaga para ativar a inteligência da equipe." href="/admin/vagas?nova=1" action="Criar vaga"/>:jobs.slice(0,4).map(job=><div key={job.id} className="flex items-start justify-between gap-3 rounded-xl border border-[var(--line)] bg-[#0c0e13] p-4"><div className="min-w-0"><p className="text-sm font-medium break-words">{job.title}</p><p className="mt-1 text-xs text-[var(--muted)] break-words">{job.company}{job.location?` · ${job.location}`:""}</p></div><div className="shrink-0 text-right"><p className="text-lg font-medium">{job.referralCount}</p><p className="text-[10px] text-[var(--muted)]">indicações</p></div></div>)}</div></section><section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4 sm:p-5"><h2 className="font-medium">Atividade recente</h2><p className="mt-1 text-xs text-[var(--muted)]">Somente ações consentidas.</p><div className="mt-5 space-y-4">{referrals.length===0?<p className="rounded-xl border border-dashed border-[var(--line)] p-5 text-center text-xs leading-5 text-[var(--muted)]">As indicações confirmadas pelos membros aparecerão aqui.</p>:referrals.slice(0,5).map(r=><div key={r.id} className="border-l border-[#5064a1] pl-3"><p className="text-sm break-words">{r.candidateName}</p><p className="mt-1 text-[10px] text-[var(--muted)] break-words">por {r.memberName} · {r.jobTitle}</p></div>)}</div></section></div></>;
}

function Empty({text,href,action}:{text:string;href:string;action:string}) { return <div className="rounded-xl border border-dashed border-[var(--line)] px-5 py-10 text-center"><p className="text-sm text-[var(--muted)]">{text}</p><Link href={href} className="mt-4 inline-block text-sm text-[#9eb2ff]">{action} →</Link></div>; }
